### ISSUE TITLE
REPORTE DE LA ENTREVISTA

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-2-entrevista-equpio-lor-xd#1]
[ENTREVISTA 1.pdf](https://github.com/user-attachments/files/16841759/ENTREVISTA.1.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 20, bien realizada

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
